<?php

namespace GSB\ObjComBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SuiviRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiviRepository extends EntityRepository
{
}
